### ISSUE TITLE
CI takes really long

### ISSUE THREAD

**Issue by carme-hp** [opendihu/opendihu#18]
In GitHub actions, it looks like we download and build all the dependencies in the `build` step. This was not intended, since it takes a lot of time. It didn't happen when using circleCI, e.g., see https://app.circleci.com/pipelines/github/maierbn/opendihu/1438/workflows/0290d16c-efb4-4c03-a782-e09b0fc988b9/jobs/1442

**Comment by MakisH** [comment]
We figured out in a meeting today why this must be happening, even after some recent improvements.

1. The https://hub.docker.com/r/carmehp/opendihu should only include the OpenDiHu core and its dependencies. This is a cloned repository and what SCons automatically installs.
2. The https://github.com/opendihu/opendihu/blob/develop/.github/workflows/unit-tests.yml should get the latest state or the repository and reuse the dependencies that SCons already built.

The problem here is that the [`actions/checkout`](https://github.com/marketplace/actions/checkout) makes a new clone into another path, ignoring the work that SCons has already done.

There are several ways out of this situation.

## Approach 1: Decouple the installation of dependencies from the OpenDiHu installation

This is something that should happen in the long run, but might be quite complicated at the moment. One could then really have a container that only includes the dependencies.

## Approach 2: Skip the `actions/checkout` and pull directly in the container

A hacky approach, but it should work.

You can use a variable such as `${{ github.event.pull_request.head.sha }}` to get the `HEAD` of the PR triggering the CI. You can read more about these variables in https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/accessing-contextual-information-about-workflow-runs

## Approach 3: Keep the `actions/checkout` and move files around

That would also be hacky, but could be a bit easier to rework in the future.

The general CI workflow would be the same, but you would move (some of) the additional files that SCons prepared in the container. If I run `git clean -idx` inside the container, these are the files that are not tracked:

```
  .sconf_temp/                                                             dependencies/scons/scons-local-4.6.0/SCons/Node/__pycache__/
  .scons_node_count                                                        dependencies/scons/scons-local-4.6.0/SCons/Platform/__pycache__/
  .sconsign.dblite                                                         dependencies/scons/scons-local-4.6.0/SCons/Scanner/__pycache__/
  .scr/                                                                    dependencies/scons/scons-local-4.6.0/SCons/Script/__pycache__/
  config.log                                                               dependencies/scons/scons-local-4.6.0/SCons/Taskmaster/__pycache__/
  core/build_release/                                                      dependencies/scons/scons-local-4.6.0/SCons/Tool/__pycache__/
  dependencies/adios/                                                      dependencies/scons/scons-local-4.6.0/SCons/Tool/linkCommon/__pycache__/
  dependencies/base64/                                                     dependencies/scons/scons-local-4.6.0/SCons/Util/__pycache__/
  dependencies/easyloggingpp/                                              dependencies/scons/scons-local-4.6.0/SCons/Variables/__pycache__/
  dependencies/googletest/                                                 dependencies/scons/scons-local-4.6.0/SCons/__pycache__/
  dependencies/hdf5/                                                       dependencies/scons/scons-local-4.6.0/SCons/compat/__pycache__/
  dependencies/libxml2/                                                    dependencies/scr/
  dependencies/nlohmannjson/                                               dependencies/semt/
  dependencies/opencor/                                                    dependencies/std_simd/
  dependencies/petsc/                                                      dependencies/vc/
  dependencies/precice/                                                    dependencies/xbraid/
  dependencies/python/                                                     examples/electrophysiology/input.tgz
  dependencies/pythonpackages/                                             examples/electrophysiology/input/
  dependencies/scons-config/sconsconfig/__pycache__/                       out.py
  dependencies/scons-config/sconsconfig/packages/__pycache__/              precice-profiling/
  dependencies/scons-config/sconsconfig/tools/__pycache__/                 stdout.log
  dependencies/scons-config/sconsconfig/utils/__pycache__/
```

Note that the `WORKDIR` of the container is `/workspace/opendihu`.

**Comment by carme-hp** [comment]
I decided to go for option 2, because of its simplicity. 

It resulted in a reduction of the test time from 90+ to 30+ minutes. The limiting factor now is the compilation of the tests.
